### PR TITLE
Add images for Scala Stream Collector 0.16.0-rc1

### PR DESCRIPTION
**Pull request by dilyand**

### CODE REVIEW

**Review by BenFradet — APPROVED** [review]
:+1:

**Comment by danielsepulvedab** [comment]
👋 Is this gonna be updated/merged to include the last versions of the collectors?

**Comment by chuwy** [comment]
Hi @danielsepulvedab! SSC images are published on DockerHub via its own CI/CD long time ago. You can grab the image you need: https://hub.docker.com/repository/docker/snowplow/scala-stream-collector-kinesis.

Going to close this PR.

**Comment by markharding** [comment]
> https://hub.docker.com/repository/docker/snowplow/scala-stream-collector-kinesis

Would it make sense to remove the scala-stream-collector-kinesis folder (or put in a deprecation notice) on this repo? I thought 0.15 was the latest version until I found this issue.

**Pull request closed without merging**
