### PR TITLE
Docker compose example

### PR DESCRIPTION
**Pull request by tromika**
As I see the last pull request is still open and I wanted to work on this.
With the Kafka support, it makes sense to use it for local testing so I focused on to create an environment with Kafka. 

There is only one image but with different entrypoints you can specify the service you want to start.

docker-compose.yml contains the container stack.

Currently, I used the r85_metamorphosis release for testing.
The current approach use mounted config files so you can push the images to https://hub.docker.com/ as well.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by tromika** [comment]
I've already signed it

**Comment by snowplowcla** [comment]
Confirmed! @tromika has signed the Individual Contributor License Agreement. Thanks so much

**Review by BenFradet — COMMENTED** [review]
Looks great :+1:

However could you open a separate PR for the docker-compose example with the configuration files?
Let's put all this into an `example` folder.

Also could you leave the `LICENSE` and `README.md` intact, we'll take care of those :+1:

**Comment by BenFradet** [comment]
Integrated into #19 , thanks :+1:

**Pull request closed without merging**
