### PR TITLE
Update base container to fix cves

### PR DESCRIPTION
**Pull request by dadasami**
This pull request aims to update base docker images in order to fix cves that are found by AWS containers scanning.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by dadasami** [comment]
> I signed it!

**Comment by dadasami** [comment]
I signed it!

**Comment by dadasami** [comment]
Hey @oguzhanunlu , thanks for great library, just wanted to post to say that I've signed the CLA (but the CLA check does not appear to automatically update) and would love a PR review when you have a chance. Cheers, Amin

**Comment by oguzhanunlu** [comment]
Thanks for taking time to improve Snowplow base images, @dadasami ! It looks good to me at a quick glance. You're right on the bot, we're aware of it and will fix soon.

We will confirm your sign on the CLA, approve your PR and incorporate into next release.

**Comment by oguzhanunlu** [comment]
Hey @dadasami , I wanted to confirm your sign and it seems you haven't signed our CLA.

Could you sign the individual CLA? It is available [here](https://docs.google.com/forms/d/e/1FAIpQLSd89YTDQ1XpTZbj3LpOkquV_h1Y8k9ay3iFbJsZsJrz18I23Q/viewform). Please make sure `GitHub Account Name` field contains your GitHub username which contributed this PR.

Thanks in advance!

**Comment by dadasami** [comment]
Hey @oguzhanunlu , you are right! CLA is signed, now.

Thanks a lot for your time.

**Comment by snowplowcla** [comment]
Confirmed! @dadasami has signed the Contributor License Agreement. Thanks so much.

**Comment by dadasami** [comment]
Hi, @oguzhanunlu , It would be great if someone can review this PR. Would you please let me know how long does it take to be merged?

**Comment by oguzhanunlu** [comment]
Hi @dadasami , thanks for signing the CLA! Your changes will be incorporated into next release, however we didn't plan it yet. Do you have an urgency on this fix?

**Comment by dadasami** [comment]
Hi @oguzhanunlu , the fix is required to address the reported critical vulnerabilities by the AWS container scan and we need to resolve all the potential security risks in our project as soon as possible. It would be a huge favor if you could help us here.

**Comment by oguzhanunlu** [comment]
Thanks for the details @dadasami , we'll check internally for a prioritization and I'll update you, possibly next week.

**Comment by oguzhanunlu** [comment]
Hey @dadasami , we've prioritized this. I'll cherry-pick your commit and incorporate into the release PR I'll open shortly. Note that your changes will not be taken as is, since the files you modified correspond to base image versions we already published. We need new versions of base images where your changes are applied. I'll take care of this, I just wanted to share the status with you. I'll close the PR after cherry-picking.

Thanks for the contribution!

**Comment by dadasami** [comment]
Hey @oguzhanunlu , Thanks a lot for reprioritization and your feedback. I'm looking forward to the next release.

**Pull request closed without merging**
