### PR TITLE
Docker files for base, elasticsearch-sink, stream-collector & stream-enrich

### PR DESCRIPTION
**Pull request by danielzohar**
Uber ZIP is downloaded in the base docker image then each docker container retains the JAR it needs and removes the rest.
Iron.io base container is used which is base on Alpine Linux. This is recommended to keep containers low in size (about 5mb + jar file)

All containers come with a default configuration file which is more or less identical to the one in the snowplow repo minus comments. The only exception is Elasticsearch since some of the parameters are domain specific like the Elasticsearch server IP address, name etc.

We should add a README as well and/or potentially an example with Docker Compose

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @danielzohar ! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

Hopefully around Snowplow Mini v0.3.0 or 0.4.0 we will start using these Docker images for each service, so we should be able to use that Docker Compose as an example: https://github.com/snowplow/snowplow-mini/issues/23

**Comment by danielzohar** [comment]
Should resolve:
https://github.com/snowplow/docker-snowplow/issues/7
https://github.com/snowplow/docker-snowplow/issues/6
https://github.com/snowplow/docker-snowplow/issues/5

and potentially https://github.com/snowplow/docker-snowplow/issues/4 as well

**Comment by danielzohar** [comment]
Np @alexanderdean should I sign the "professional"  CLA or the personal one?

**Comment by alexanderdean** [comment]
Hi @danielzohar - as the PR comes from Memrise org, I think the "professional" one would fit best...

**Comment by danielzohar** [comment]
yeah, I guess that was a stupid question :) I'm just not very good at lawyer-speak.

Anyhow, signed!

**Comment by alexanderdean** [comment]
Confirmed! And thanks for being the driving force for getting Snowplow on the Docker container ship... It's appreciated!

**Comment by danielzohar** [comment]
My pleaure!

**Comment by alexanderdean** [comment]
Hey @danielzohar - just going through this in our weekly infra meeting. What are your thoughts around the application configurations? Are the ones you've included just examples? How should we be thinking about configuration references in a Docker world?

**Comment by danielzohar** [comment]
Hi @alexanderdean 
The best practice with Docker (to the best of my knowledge) is to provide default configuration files that can be easily overridden by mounting an alternative configuration files. That's what I did for all the container beside for ES where some of the parameters will always vary between installations.

For example. Running the collector with custom configuration might look like this:

```
docker run --name snowplow_collector \
        --publish 80:80 \
        --volume /etc/snowplow/collector.conf:/etc/snowplow/collector.conf \
        --d snowplow_collector
```

Note the `--volume` part. It can also be used the mount an entire folder - `--volume /etc/snowplow/:/etc/snowplow/`.

Another best practice is to allow overriding stuff with env variables but that will require something that templates the configuration files or some kind of application support.

Let me know if I can help further

**Comment by alexanderdean** [comment]
Many thanks @danielzohar - that's helpful to understand!

**Comment by shin-nien** [comment]
> Another best practice is to allow overriding stuff with env variables but that will require something that templates the configuration files or some kind of application support.

@danielzohar Afaik all the Snowplow parts written in Scala use HOCON so once https://github.com/snowplow/snowplow/pull/2798 gets merged in you'll be able to do exactly what you say above.

**Comment by BenFradet** [comment]
incorportated into #19, thanks again! :+1:

**Pull request closed without merging**
