### PR TITLE
PROTOTYPE: Move default config into the image and run by ENV variables.

### PR DESCRIPTION
**Pull request by christoph-buente**
This is a simple approach to deliver an image with already working config with sensible defaults wich can be overridden by environment variables.

This is not a real PR, just there to demonstrate my thoughts around to make running the snowplow stack with docker easier.

@alexanderdean @BenFradet @chuwy let me know, what you think.

### CODE REVIEW

**Comment by snowplowcla** [comment]
@christoph-buente  has signed the Software Grant and Corporate Contributor License Agreement

**Review by BenFradet — COMMENTED** [review]
looks pretty good, the question is do we have to supply all those env variables or could we have fallback values?

**Comment by christoph-buente** [comment]
All ENV variables are optional. If not present, they will fallback to the defaults. This in done with this syntax:
`port = 8080`
`port = ${?COLLECTOR_PORT}`

The questionmark makes the substitution optional. So  technically, your could just do a docker run with passing config and without env variable and it will work immediately out of the box. In the README i ommited some parameters intentionally, to showcase.

**Comment by BenFradet** [comment]
>All ENV variables are optional. If not present, they will fallback to the defaults. This in done with this syntax:
port = 8080
port = ${?COLLECTOR_PORT}

My bad I completely missed the fact that the properties were duplicated...
Then I think it'd be great to have that for the latest images wdyt? Or is this something you envision for the next images?

**Comment by christoph-buente** [comment]
And the configs could also be specific to the log service for example kinesis. The nsq part does not have to be in there, for example. And as i said, if we name this default-config.hocon and make use of it, in case no dedicated config is supplied, the call command would be tremendously easier to run. Also on ECS, Beanstalk or kubernetes

**Comment by BenFradet** [comment]
>And the configs could also be specific to the log service for example kinesis. The nsq part does not have to be in there, for example.

yup we'd definitely need one config per targeted platform

**Comment by christoph-buente** [comment]
Great to be aligned. How can we move things forward? I don't think we are into the topic deep enought to provide a real PR. @alexanderdean can you prioritize?

**Comment by alexanderdean** [comment]
Let's make it a part of the next release.

**Comment by christoph-buente** [comment]
OK, deal!

**Comment by BenFradet** [comment]
logged #69

**Pull request closed without merging**
