### PR TITLE
Deployment of Postgres and Snowplow Iglu server on Kubernetes

### PR DESCRIPTION
**Pull request by drejahl**
I deployed Postgres and the Snowplow Iglu 0.4.0 server on a Kubernetes cluster and I would like to share the required configuration files.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by BenFradet** [comment]
Hey @drejahl , could you sign the CLA so we can schedule the PR into the next release?

**Comment by drejahl** [comment]
Hi @BenFradet, please give me another couple of days and I will do.

**Comment by drejahl** [comment]
@BenFradet @snowplowcla I signed the CLA.

**Comment by snowplowcla** [comment]
Confirmed! @drejahl  has signed the Individual Contributor License Agreement. Thanks so much

**Review by BenFradet — APPROVED** [review]
Thanks, I will incorporate it into #111 :+1:

**Comment by BenFradet** [comment]
incorporate into #111 , thanks!

**Pull request closed without merging**
